### ISSUE TITLE
Not able to link files

### ISSUE THREAD

**Issue by Krylol94** [LEDAcrypt/LEDApkc#1]
Hello everybody, 
I tried to use the files contained in Reference Implementation within a main.cpp file I created, but I had an issue since when I use the function to generate Qpos and Hpos the main was not able to found the functions even if the libraries were included.

**Comment by alexrow** [comment]
To be able to call C code from C++ you should instruct the compiler so that it is aware that the symbols are not mangled according to the C++ convention.
In practice, it is sufficient to encase the headerfiles you want to include in an extern "C" block as follows.

```
extern "C" {
#include "my_header.h"
}
```

**Comment by Krylol94** [comment]
Thank you so much for the reply.

**Comment by alexrow** [comment]
I'm closing the issue as it looks solved.
